// PATIENT
export const FETCH_PATIENT_REQUEST = "FETCH_PATIENT_REQUEST";
export const FETCH_PATIENT_SUCCESS = "FETCH_PATIENT_SUCCESS";
export const FETCH_PATIENT_FAILED = "FETCH_PATIENT_FAILED";

export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const UPDATE_PATIENT_SUCCESS = "UPDATE_PATIENT_SUCCESS";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DISABLE_PATIENT_SUCCESS = "DISABLE_PATIENT_SUCCESS";

// DENTIST
export const FETCH_DENTIST_REQUEST = "FETCH_DENTIST_REQUEST";
export const FETCH_DENTIST_SUCCESS = "FETCH_DENTIST_SUCCESS";
export const FETCH_DENTIST_FAILED = "FETCH_DENTIST_FAILED";

export const CREATE_DENTIST_SUCCESS = "CREATE_DENTIST_SUCCESS";

//ADMIN
export const FETCH_ADMIN_REQUEST = "FETCH_ADMIN_REQUEST";
export const FETCH_ADMIN_SUCCESS = "FETCH_ADMIN_SUCCESS";
export const FETCH_ADMIN_FAILED = "FETCH_ADMIN_FAILED";

export const FETCH_LOGIN_ADMIN_REQUEST = "FETCH_LOGIN_ADMIN_REQUEST";
export const CREATE_ADMIN_SUCCESS = "CREATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const DELETE_ADMIN_SUCCESS = "DELETE_ADMIN_SUCCESS";
export const ADMIN_CHANGE_STATUS_SUCCESS = "ADMIN_CHANGE_STATUS_SUCCESS";
export const FETCH_LOGIN_ADMIN_SUCCESS = "FETCH_LOGIN_ADMIN_SUCCESS";
export const FETCH_LOGIN_ADMIN_FAILED = "FETCH_LOGIN_ADMIN_FAILED";

//SERVICES
export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILED = "FETCH_SERVICES_FAILED";

export const CREATE_SERVICES_SUCCESS = "CREATE_SERVICES_SUCCESS";
export const UPDATE_SERVICES_SUCCESS = "UPDATE_SERVICES_SUCCESS";
export const DELETE_SERVICES_SUCCESS = "DELETE_SERVICES_SUCCESS";

//PAYMENT
export const FETCH_PAYMENT_REQUEST = "FETCH_PAYMENT_REQUEST";
export const FETCH_PAYMENT_SUCCESS = "FETCH_PAYMENT_SUCCESS";
export const FETCH_PAYMENT_FAILED = "FETCH_PAYMENT_FAILED";

export const APPROVED_PAYMENT_SUCCESS = "APPROVED_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";

//APPOINTMENT
export const FETCH_APPOINTMENT_REQUEST = "FETCH_APPOINTMENT_REQUEST";
export const FETCH_APPOINTMENT_SUCCESS = "FETCH_APPOINTMENT_SUCCESS";
export const FETCH_APPOINTMENT_FAILED = "FETCH_APPOINTMENT_FAILED";

export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAILED = "CREATE_APPOINTMENT_FAILED";

export const APPROVED_APPOINTMENT_SUCCESS = "APPROVED_APPOINTMENT_SUCCESS";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENT_SUCCESS";
export const CANCELLED_APPOINTMENT_SUCCESS = "CANCELLED_APPOINTMENT_SUCCESS";
export const DONE_APPOINTMENT_SUCCESS = "DONE_APPOINTMENT_SUCCESS";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS";

//ANNOUNCEMENT
export const FETCH_ANNOUNCEMENT_REQUEST = "FETCH_ANNOUNCEMENT_REQUEST";
export const FETCH_ANNOUNCEMENT_SUCCESS = "FETCH_ANNOUNCEMENT_SUCCESS";
export const FETCH_ANNOUNCEMENT_FAILED = "FETCH_ANNOUNCEMENT_FAILED";

//INSTALLMENT
export const FETCH_INSTALLMENT_REQUEST = "FETCH_INSTALLMENT_REQUEST";
export const FETCH_INSTALLMENT_SUCCESS = "FETCH_INSTALLMENT_SUCCESS";
export const FETCH_INSTALLMENT_FAILED = "FETCH_INSTALLMENT_FAILED";

//HISTORY
export const FETCH_HISTORY_REQUEST = "FETCH_HISTORY_REQUEST";
export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_FAILED = "FETCH_HISTORY_FAILED";

//NOTIFICATION
export const FETCH_NOTIFICATION_REQUEST = "FETCH_NOTIFICATION_REQUEST";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILED = "FETCH_NOTIFICATION_FAILED";

export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";

//MESSAGE
export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILED = "FETCH_MESSAGE_FAILED";

export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

export const RESPONSE_MESSAGE_SUCCESS = "RESPONSE_MESSAGE_SUCCESS";

//FEE
export const FETCH_FEE_REQUEST = "FETCH_FEE_REQUEST";
export const FETCH_FEE_SUCCESS = "FETCH_FEE_SUCCESS";
export const FETCH_FEE_FAILED = "FETCH_FEE_FAILED";

//SCHEDULE
export const FETCH_SCHEDULE_REQUEST = "FETCH_SCHEDULE_REQUEST";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILED = "FETCH_SCHEDULE_FAILED";

export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS";
export const CREATE_SCHEDULE_FAILED = "CREATE_SCHEDULE_FAILED";

export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS";
export const UPDATE_SCHEDULE_FAILED = "UPDATE_SCHEDULE_FAILED";

export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";
export const DELETE_SCHEDULE_FAILED = "DELETE_SCHEDULE_FAILED";
